### ISSUE TITLE
A translation string missing

### ISSUE THREAD

**Issue by dashinfantry** [monich/harbour-mybackup#8]
"Add backup item"

**Comment by monich** [comment]
I guess you just missed it:

https://github.com/monich/harbour-mybackup/blob/ea4a0a6/translations/harbour-mybackup-zh_CN.ts#L69

Please submit a PR or let me know what it should be. Goggle translate suggests 添加备份项目

**Comment by dashinfantry** [comment]
Yes it's"添加备份项目".I don't know why I can't edit Chinese translation now.

**Comment by monich** [comment]
[Done](https://github.com/monich/harbour-mybackup/commit/46d70d3). That change will get into the next version, whenever I decide to build it. Thanks!
