### ISSUE TITLE
Backing up files outside home directory

### ISSUE THREAD

**Issue by flossgeek** [monich/harbour-mybackup#9]
Hello,
Is it possible to backup files from outside the home directory? I, for example want to backup a file that is stored in `/home/.android`, but have not found a way to do so via the interface of your app. 
Thanks!

**Comment by monich** [comment]
The problem with files/directories outside of home is that even a privileged user process may not be able to access those - even for reading, let alone writing. Would a symlink do the trick in your case?

**Comment by flossgeek** [comment]
Yes, I've thought about that. If there is no other way around it I'm going to try that.
But I was wondering, isn't it possible to achieve backing up any directory with the openrepos-mybackup command line interface (running as root)? I haven't figured out exactly how it's supposed to work. How do I tell it to add a file to the system backup?

If I run it like this: `openrepos-mybackup --action=export --home-dir=<file_to_backup> --dir=<target_dir>`, there is only a single `config.json` file stored under `<target_dir>/users/100000` with some keys, which appear to be items from the main backup. How do all these things relate?

**Comment by monich** [comment]
The list of things to backup is fetched from `~/.local/share/openrepos-mybackup/backup.json`, that file is supposed to be generated by My Backup UI which user launches from the app grid.

`config.json` is the backup of the dconf keys.

`--home-dir` takes the home directory as a parameter, e.g. `--home-dir=/home/defaultuser`. It could be optional but I never thought that anyone would ever want to run this tool manually from the command line. It's supposed to be launched by the backup process (which starts when you press "Back up now" button in Settings => System => Backup).

**Comment by flossgeek** [comment]
Okay, so that command is a separate backup that exports the dconf keys from the specified home-dir to the specified backup location (--dir)? Then I'll have to go the symlinks route anyway I suppose.

**Comment by monich** [comment]
[This file](/monich/harbour-mybackup/blob/master/openrepos-mybackup.json) gets installed to `/usr/share/jolla-vault/units/` to register this app with the backup system. The backup system then calls it with a particular command line (and it runs silently in the background). Without that command line, it launches a full-blown UI to edit its own config.

**Comment by flossgeek** [comment]
Alright, nice mechanism. So the cli is only really used by the system to create a backup. Thanks for explaining.
